# Default configuration for transformer model training
model_name: "transformer_default"

# Data parameters
data_dir: "/fs/ddn/sdf/group/atlas/d/liangyu/jetML/datasets/h5/selected_h5_old_files/"
num_files: 50
max_cells: 40
min_cells: 3
cell_selection_feature: "Cell_e"

# Feature selection parameters
use_spatial_features: false
use_track_features: true        # Include track matching features
use_jet_features: false         # Exclude jet matching features (default dataset doesn't have jets)

# Cell filtering parameters
require_valid_cells: true
use_cell_track_matching: true   # Use track matching filter
use_cell_jet_matching: false    # Disable jet matching filter (default dataset doesn't have jets)
additional_cell_filters: {}

# Detector calibration parameters (disabled by default)
use_detector_params: false
calibration_data_file: "HStrackmatching_calibration.txt"

# Calibration validation parameters
calibration_validation: false
validation_detector_type: 1  # 1=barrel, 0=endcap
validation_layer: 1  # 1, 2, or 3
gaussian_fit_range: 120  # Range for Gaussian fitting in baseline checks

# Data split parameters
test_size: 0.3
val_split: 0.33333
random_state: 42

# Model architecture parameters
d_model: 128  # Must be divisible by num_heads
num_heads: 8
dff: 256
num_transformer_blocks: 3
dropout_rate: 0.1

# Dense layer parameters
vertex_dense_units: 64
final_dense_units: [256, 128, 64]
final_dropout_rates: [0.3, 0.2, 0.1]
use_batch_norm: true

# Training parameters
batch_size: 64
epochs: 50
learning_rate: 0.0001
lr_reduction_factor: 0.5
early_stopping_patience: 15
lr_patience: 5
min_lr: 0.0000001

# Feature definitions
spatial_features: ["Cell_x", "Cell_y", "Cell_z"]
vertex_spatial_features: ["HSvertex_reco_x", "HSvertex_reco_y", "HSvertex_reco_z"]
all_cell_features:
  - "Cell_x"
  - "Cell_y" 
  - "Cell_z"
  - "Cell_eta"
  - "Cell_phi"
  - "Cell_Barrel"
  - "Cell_layer"
  - "Cell_time_TOF_corrected"
  - "Cell_e"
  - "Cell_significance"
track_features:
  - "matched_track_pt"
  - "matched_track_deltaR"
jet_features:
  - "matched_jet_pt"
  - "matched_jet_eta"
  - "matched_jet_phi"
  - "matched_jet_width"
  - "matched_jet_deltaR"
skip_normalization: ["Cell_time_TOF_corrected", "Cell_Barrel", "Cell_layer"]
