# Fast testing configuration for development and debugging
model_name: "transformer_fast_test"

# Data parameters
data_dir: "../selected_h5_with_jets/"
num_files: 3  # Reduced for fast testing
max_cells: 50  # Reduced for faster processing
min_cells: 1
cell_selection_feature: "Cell_e"

# Feature selection parameters
use_spatial_features: true
use_track_features: false      
use_jet_features: true         

# Cell filtering parameters
require_valid_cells: true
use_cell_track_matching: false
use_cell_jet_matching: true
additional_cell_filters: {}

# Detector calibration parameters - enabled for testing
use_detector_params: true
calibration_data_file: "cell_jet_calibration.txt"

# Calibration validation parameters - enabled for fast testing
calibration_validation: true
validation_detector_type: 1  # 1=barrel, 0=endcap  
validation_layer: 2  # 1, 2, or 3
gaussian_fit_range: 120  # Range for Gaussian fitting in baseline checks

# Data split parameters
test_size: 0.2  # Smaller test set for faster processing
val_split: 0.25  # 25% of test_size for validation
random_state: 42

# Model architecture parameters - small but functional
d_model: 32  # Must be divisible by num_heads
num_heads: 4  # Reduced for faster training
dff: 64
num_transformer_blocks: 2
dropout_rate: 0.1

# Dense layer parameters - minimal network
vertex_dense_units: 8
final_dense_units: [16, 8]  # Simplified architecture
final_dropout_rates: [0.1, 0.05]
use_batch_norm: true

# Training parameters - fast training
batch_size: 32  # Smaller batch for faster iterations
epochs: 3  # Increased from 10 for meaningful training
learning_rate: 0.001  # Higher LR for faster convergence
lr_reduction_factor: 0.5
early_stopping_patience: 8
lr_patience: 3
min_lr: 0.0000001

# Feature definitions
spatial_features: ["Cell_x", "Cell_y", "Cell_z"]
vertex_spatial_features: ["HSvertex_reco_x", "HSvertex_reco_y", "HSvertex_reco_z"]
all_cell_features:
  - "Cell_x"
  - "Cell_y" 
  - "Cell_z"
  - "Cell_eta"
  - "Cell_phi"
  - "Cell_Barrel"
  - "Cell_layer"
  - "Cell_time_TOF_corrected"
  - "Cell_e"
  - "Cell_significance"
track_features:
  - "matched_track_pt"
  - "matched_track_deltaR"
jet_features:
  - "matched_jet_pt"
  - "matched_jet_eta"
  - "matched_jet_phi"
  - "matched_jet_width"
  - "matched_jet_deltaR"
skip_normalization: ["Cell_time_TOF_corrected", "Cell_Barrel", "Cell_layer"]
