# Fast testing configuration for development and debugging
model_name: "transformer_fast_test"

# Data parameters - minimal for fast testing
data_dir: "../selected_h5/"
num_files: 5  # Reduced from 3 to 5 for better testing
max_cells: 20  # Reduced from 10 to 20 for realistic testing
min_cells: 1
cell_selection_feature: "Cell_e"
use_spatial_features: true

# Detector calibration parameters - enabled for testing
use_detector_params: true
emb1_params: [48.5266, 37.56, 28.9393, 23.1505, 18.5468, 13.0141, 8.03724]
emb2_params: [46.2244, 41.5079, 38.5544, 36.9812, 31.2718, 29.7469, 19.331]
emb3_params: [104.325, 106.119, 71.1017, 75.151, 51.2334, 48.2088, 46.6502]
eme1_params: [125.348, 102.888, 86.7558, 59.7355, 55.3299, 41.3032, 23.646]
eme2_params: [272.149, 224.475, 173.443, 135.829, 113.05, 83.8009, 37.1829]
eme3_params: [189.356, 140.293, 111.232, 86.8784, 69.0834, 60.5034, 38.5008]

# Calibration validation parameters - enabled for fast testing
calibration_validation: true
validation_detector_type: 1  # 1=barrel, 0=endcap  
validation_layer: 2  # 1, 2, or 3
gaussian_fit_range: 120  # Range for Gaussian fitting in baseline checks

# Cell filtering parameters
use_cell_track_matching: true
require_valid_cells: true
additional_cell_filters: {}

# Data split parameters
test_size: 0.2  # Smaller test set for faster processing
val_split: 0.25  # 25% of test_size for validation
random_state: 42

# Model architecture parameters - small but functional
d_model: 32  # Must be divisible by num_heads
num_heads: 4  # Reduced for faster training
dff: 64
num_transformer_blocks: 2
dropout_rate: 0.1

# Dense layer parameters - minimal network
vertex_dense_units: 8
final_dense_units: [16, 8]  # Simplified architecture
final_dropout_rates: [0.1, 0.05]
use_batch_norm: true

# Training parameters - fast training
batch_size: 32  # Smaller batch for faster iterations
epochs: 15  # Increased from 10 for meaningful training
learning_rate: 0.001  # Higher LR for faster convergence
lr_reduction_factor: 0.5
early_stopping_patience: 8
lr_patience: 3
min_lr: 0.0000001

# Feature definitions
spatial_features: ["Cell_x", "Cell_y", "Cell_z"]
vertex_spatial_features: ["HSvertex_reco_x", "HSvertex_reco_y", "HSvertex_reco_z"]
all_cell_features:
  - "Cell_x"
  - "Cell_y" 
  - "Cell_z"
  - "Cell_eta"
  - "Cell_phi"
  - "Cell_Barrel"
  - "Cell_layer"
  - "Cell_time_TOF_corrected"
  - "Cell_e"
  - "Cell_significance"
  - "matched_track_pt"
  - "matched_track_deltaR"
skip_normalization: ["Cell_time_TOF_corrected", "Cell_Barrel", "Cell_layer"]
